apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-<% .ID %>
  labels:
    jobgroup: countdown
spec:
  completions: 2
  parallelism: 2
  completionMode: Indexed
  template:
    metadata:
      annotations:
        rt-preemptive.scheduling.x-k8s.io/ddl: <% .DDL %>
        rt-preemptive.scheduling.x-k8s.io/exec-time: <% .ExecutionTime %>
      name: countdown
      labels:
        id: "<% .ID %>"
        jobgroup: countdown
    spec:
      containers:
        - name: counter
          resources:
            requests:
              cpu: 2
            limits:
              cpu: 2
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in {<% .Meta1 %>..1}; do echo $i; sleep 1; done"
      restartPolicy: Never
