apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-$ID
  labels:
    jobgroup: countdown
spec:
  template:
    metadata:
      annotations:
        rt-preemptive.scheduling.x-k8s.io/ddl: $DDL
        rt-preemptive.scheduling.x-k8s.io/exec-time: $EXEC_TIMEs
      name: countdown
      labels:
        jobgroup: countdown
        scheduling.x-k8s.io/pod-group: countdown
    spec:
      containers:
        - name: counter
          resources:
            requests:
              memory: "100Mi"
              cpu: "200m"
            limits:
              memory: "100Mi"
              cpu: "200m"
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in {$EXEC_TIME..1}; do echo $i; sleep 1; done"
      restartPolicy: Never
