apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-$ID
  labels:
    jobgroup: countdown
spec:
  template:
    metadata:
      annotations:
        simpleddl.scheduling.x-k8s.io/ddl: $DDLs
      name: countdown
      labels:
        jobgroup: countdown
    spec:
      containers:
        - name: counter
          resources:
            requests:
              cpu: 2
            limits:
              cpu: 2
          image: centos:7
          command:
            - "bin/bash"
            - "-c"
            - "for i in {3600..1}; do echo $i; sleep 1; done"
      restartPolicy: Never
