apiVersion: v1
kind: Pod
metadata:
  name: stress-$ID
  annotations:
    rt-preemptive.scheduling.x-k8s.io/ddl: $DDL
    simpleddl.scheduling.x-k8s.io/ddl: $DDL
  labels:
    jobgroup: stress
spec:
  containers:
  - name: stress
    image: progrium/stress:latest
    resources:
      requests:
        cpu: 3
    command:
      - "stress"
      - "-c"
      - "1"
      - "-m"
      - "1"
      - "--vm-bytes"
      - "1000000000"
      - "--timeout"
      - "3600"
