apiVersion: batch/v1
kind: Job
metadata:
  name: video-transcoding-<% .InputFile %>
  labels:
    jobgroup: video-transcoding
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  template:
    metadata:
      annotations:
        rt-preemptive.scheduling.x-k8s.io/ddl: <% .DDL %>s
        rt-preemptive.scheduling.x-k8s.io/exec-time: <% .ExecutionTime %>s
    spec:
      restartPolicy: Never
      containers:
        - name: video-transcoding
          image: video-transcoding:latest
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 4
          command:
            - python
            - transcode.py
            - /mnt/videos/<% .InputFile %>.<% .InputFileExt %> # input file path
            - /mnt/videos/<% .InputFile %>/transcoded # output file path
            - $(JOB_COMPLETION_INDEX)
          volumeMounts:
            - name: videos
              mountPath: /mnt
      volumes:
        - name: videos
          persistentVolumeClaim:
            claimName: nfs
