apiVersion: batch/v1
kind: Job
metadata:
  name: video-transcoding-<% .Meta1 %>
  labels:
    jobgroup: video-transcoding
spec:
  completions: 3
  parallelism: 3
  completionMode: Indexed
  backoffLimitPerIndex: 3
  maxFailedIndexes: 3
  template:
    metadata:
      labels:
        id: "<% .ID %>"
      annotations:
        rt-preemptive.scheduling.x-k8s.io/ddl: <% .DDL %>
        rt-preemptive.scheduling.x-k8s.io/exec-time: <% .ExecutionTime %>
    spec:
      restartPolicy: Never
      priorityClassName: <% .Priority %>
      containers:
        - name: video-transcoding
          image: video-transcoding:latest
          imagePullPolicy: Never
          resources:
            limits:
              cpu: <% .CPULimit %>
            requests:
              cpu: 3
          command:
            - python
            - transcode.py
            - /mnt/videos/<% .Meta1 %>.<% .Meta2 %> # input file path
            - /mnt/videos/<% .Meta1 %>/transcoded # output file path
            - $(JOB_COMPLETION_INDEX)
          volumeMounts:
            - name: videos
              mountPath: /mnt
      volumes:
        - name: videos
          persistentVolumeClaim:
            claimName: nfs
