apiVersion: batch/v1
kind: Job
metadata:
  name: video-transcoding-indexed
spec:
  completions: 5
  parallelism: 5
  completionMode: Indexed
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: video-transcoding
          image: video-transcoding:latest
          imagePullPolicy: Never
          command:
            - python
            - transcode.py
            - /mnt/input.mp4
            - /mnt/transcoded/output.mov
            - "5"
            - $(JOB_COMPLETION_INDEX)
          volumeMounts:
            - name: videos
              mountPath: /mnt
      volumes:
        - name: videos
          persistentVolumeClaim:
            claimName: local-pvc
